### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by semey102** [ProPra16/programmierpraktikum-abschlussprojekt-info-noobs#1]
Hallo zusammen,

ich bin euer Korrektor für das Gruppenprojekt. Ich würde mich gerne am Montag 12:20 oder 14:20 in 25.12.00.82 (Computerraum) kurz mit euch treffen. Das ganze wird ca. 10min dauern.

Könnt ihr mir bitte kurz bescheidgeben, ob der Termin für euch alle passt.

Gruß Sebastian

**Comment by mespr100** [comment]
Der Termin würde für mich passen

LG Merlin

**Comment by alexteusz** [comment]
Hi, 

ja passt. 

Mit freundlichen Grüßen 
Alex Teusz

**Comment by semey102** [comment]
Ok. Dann treffen wir uns Morgen (Montag 04.07) 12:20 in 25.12.00.82 (Computerraum).

**Comment by semey102** [comment]
Der Raum ist der raum, in dem auch die Übungen stattfinden.

**Comment by semey102** [comment]
Bzgl. Gradle lest ihr euch am besten mal die Seite von Gradle durch (gradle.org/getting-started-gradle-java/). Für Travis CI gibt es etwas ähnliches findet ihr auch direkt auf deren Seite, ansonsten findet man bei Google auch einige Sachen dazu.
